//
//  Donation.Swift
//  sddProject
//
//  Created by ITP312Grp2 on 29/7/20.
//  Copyright © 2020 ITP312Grp2. All rights reserved.
//

import UIKit

class Donation: Codable {
    
    var donationID : String
    var donationName : String
    var donationImage : String
    var donationQuantity : String
    
//    init(_ donationID: String, _ donationName: String, _ donationImage: String, _ donationQuantity: String)
//    {
//        self.donationID = donationID
//        self.donationName = donationName
//        self.donationImage = donationImage
//        self.donationQuantity = donationQuantity
//    }

}
